name: gofit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 1. State Management (Untuk simpan Nama User)
  provider: ^6.1.5+1

  # 2. Firebase (Versi Baru)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # 3. Internet & Format (Untuk Cuaca & Tanggal)
  http: ^1.1.0
  intl: ^0.20.2

  # 4. Icons
  cupertino_icons: ^1.0.8
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Pastikan folder dan gambarnya sudah ada
  assets:
    - assets/image/