// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Vk-vYBcAuLwN9arq7IwcNHsd4UW-2bo',
    appId: '1:105072351264:web:25da8707548da7f53b0445',
    messagingSenderId: '105072351264',
    projectId: 'go-fit-c36e8',
    authDomain: 'go-fit-c36e8.firebaseapp.com',
    storageBucket: 'go-fit-c36e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDse4kElfUNJQXcA_sOuGJkFAmEQF5DxcU',
    appId: '1:105072351264:android:60dd848b197ddfc33b0445',
    messagingSenderId: '105072351264',
    projectId: 'go-fit-c36e8',
    storageBucket: 'go-fit-c36e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCY2sAkayg3ZC9rWi27LTikUkub20MrRw',
    appId: '1:105072351264:ios:52848a7abc5dd7083b0445',
    messagingSenderId: '105072351264',
    projectId: 'go-fit-c36e8',
    storageBucket: 'go-fit-c36e8.firebasestorage.app',
    iosClientId: '105072351264-j25188a9donqopt6ug9g1vssnb6t7073.apps.googleusercontent.com',
    iosBundleId: 'com.gofit.gofit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCY2sAkayg3ZC9rWi27LTikUkub20MrRw',
    appId: '1:105072351264:ios:eb897dafb2104ddf3b0445',
    messagingSenderId: '105072351264',
    projectId: 'go-fit-c36e8',
    storageBucket: 'go-fit-c36e8.firebasestorage.app',
    iosClientId: '105072351264-advk0eee9n2edgs824e66lecdmu7arpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gofit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Vk-vYBcAuLwN9arq7IwcNHsd4UW-2bo',
    appId: '1:105072351264:web:f64788b7b80bb9933b0445',
    messagingSenderId: '105072351264',
    projectId: 'go-fit-c36e8',
    authDomain: 'go-fit-c36e8.firebaseapp.com',
    storageBucket: 'go-fit-c36e8.firebasestorage.app',
  );
}
